/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
By considering the terms in the Fibonacci sequence whose values do not exceed N, find the sum of the even-valued terms.
1,2,3,5,8,13,21,34,55,89...
Input Format
First line contains T that denotes the number of test cases. This is followed by T lines, each containing an integer, N.

Output Format
Print the required answer for each test case.

Sample Input
2
10
100

Sample Output
10
44
*/
#include <cmath>
#include <cstdio>
#include <vector>
#include <iostream>
#include <algorithm>
using namespace std;
long* calc(long *a,long *b){
    *b=*a+*b;
    *a=*b-*a;
    return b;
}


int main() {
    long T,*N,i,sum=0,a=0,b=1;
    cin>>T;
    N=(long *)malloc(T*sizeof(long));    
    for(i=0;i<T;i++){
        cin>>*(N+i);
    }
   for(i=0;i<T;i++){
       a=0,b=1,sum=0;
       while(*(calc(&a,&b))<*(N+i)){
           if(b%2==0)          
           sum+=b;
       }
       cout<<sum<<endl;
   }
}
